import streamlit as st
import streamlit.components.v1 as components
import pandas as pd
import numpy as np
import joblib
from sklearn.decomposition import PCA
import plotly.express as px
import plotly.graph_objects as go
import os # Import os module for path manipulation

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
MODELS_DIR = PROJECT_ROOT / "src" / "model"

@st.cache_data
def load_data():
    """Loads the processed DataFrame."""
    file_path = MODELS_DIR / "df_processed.pkl"
    try:
        return pd.read_pickle(file_path).reset_index(drop=True)
    except FileNotFoundError:
        st.error(f"Error: Data file not found at '{file_path}'. Please ensure 'df_processed.pkl' is generated by autoencoder.py and is located in the expected directory: '{MODELS_DIR}'.")
        st.stop() # Stop the app if essential file is missing
    except Exception as e:
        st.error(f"Error loading data from '{file_path}': {e}")
        st.stop()

@st.cache_data
def load_latent_features():
    """Loads the latent features generated by the autoencoder."""
    file_path = MODELS_DIR / "latent_features.npy"
    try:
        return np.load(file_path)
    except FileNotFoundError:
        st.error(f"Error: Latent features file not found at '{file_path}'. Please ensure 'latent_features.npy' is generated and is located in the expected directory: '{MODELS_DIR}'.")
        st.stop()
    except Exception as e:
        st.error(f"Error loading latent features from '{file_path}': {e}")
        st.stop()

@st.cache_resource
def load_knn_model():
    """Loads the trained KNN model."""
    file_path = MODELS_DIR / "knn_model.pkl"
    try:
        return joblib.load(file_path)
    except FileNotFoundError:
        st.error(f"Error: KNN model file not found at '{file_path}'. Please ensure 'knn_model.pkl' is generated and is located in the expected directory: '{MODELS_DIR}'.")
        st.stop()
    except Exception as e:
        st.error(f"Error loading KNN model from '{file_path}': {e}")
        st.stop()

@st.cache_data
def calculate_pca(latent_features, n_components=3):
    """Performs PCA on latent features for visualization."""
    if latent_features.shape[0] == 0:
        st.warning("Cannot perform PCA: Latent features array is empty.")
        return np.array([])
    pca = PCA(n_components=n_components)
    components = pca.fit_transform(latent_features)
    return components

@st.cache_data
def calculate_correlation(df, numeric_features):
    """Calculates the correlation matrix for numeric features."""
    # Ensure all numeric features exist in the DataFrame before calculating correlation
    existing_numeric_features = [f for f in numeric_features if f in df.columns]
    if not existing_numeric_features:
        st.warning("No numeric features found for correlation calculation.")
        return pd.DataFrame() # Return empty DataFrame if no features exist
    return df[existing_numeric_features].corr()


# Define numeric features (should match what was used in autoencoder.py after encoding)
numeric_features = [
    'danceability', 'energy', 'loudness', 'speechiness',
    'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
    'track_genre_encoded'
]

# Set Streamlit page configuration
st.set_page_config(page_title="Spotify Recommender", layout="wide")
st.title("🎧 Music Recommender")

# Create tabs for different functionalities
tab1, tab2 = st.tabs(["🎵 Recommendations", "📊 Genre Visualization"])

def plot_heatmap(df_for_plot, features_for_plot):
    """
    Generates a heatmap visualizing the correlation between numeric features.
    Args:
        df_for_plot (DataFrame): The DataFrame containing the data.
        features_for_plot (list): List of numeric feature names.
    Returns:
        plotly.graph_objects.Figure: The heatmap figure.
    """
    corr = calculate_correlation(df_for_plot, features_for_plot)
    if corr.empty:
        st.warning("Cannot plot heatmap: No valid numeric features or empty correlation matrix.")
        return go.Figure()

    fig = go.Figure(data=go.Heatmap(
        z=corr.values,
        x=features_for_plot,
        y=features_for_plot,
        colorscale='RdBu',
        zmin=-1,
        zmax=1,
        text=np.round(corr.values, 2),
        texttemplate='%{text}',
        hoverongaps=False
    ))
    fig.update_layout(
        title='Feature Correlation Heatmap',
        width=700,
        height=700,
        xaxis_tickangle=-45
    )
    return fig

def plot_latent_3d(latent_features, df_for_plot):
    """
    Visualizes tracks in a 3D space using PCA, colored by genre.
    Args:
        latent_features (NumPy array): Latent features of the tracks.
        df_for_plot (DataFrame): DataFrame containing track information.
    Returns:
        plotly.graph_objects.Figure: The 3D scatter plot figure.
    """
    if latent_features.shape[0] == 0 or df_for_plot.empty:
        st.warning("Cannot plot 3D visualization: Latent features or DataFrame is empty.")
        return go.Figure()

    components = calculate_pca(latent_features)
    if components.shape[0] == 0: # Check if PCA returned an empty array
        return go.Figure() # Return empty figure if PCA failed or input was empty

    plot_df = pd.DataFrame(components, columns=['PC1', 'PC2', 'PC3'])
    
    # Ensure 'track_genre', 'track_name', 'artists' exist in df_for_plot
    # and align with the number of rows in components
    if 'track_genre' in df_for_plot.columns and len(df_for_plot) == len(components):
        plot_df['Genre'] = df_for_plot['track_genre']
    else:
        plot_df['Genre'] = 'Unknown' # Fallback
        st.warning("Track genre column not found or row count mismatch for 3D plot. Using 'Unknown' genre.")

    if 'track_name' in df_for_plot.columns and len(df_for_plot) == len(components):
        plot_df['Track'] = df_for_plot['track_name']
    else:
        plot_df['Track'] = 'Unknown Track'
    
    if 'artists' in df_for_plot.columns and len(df_for_plot) == len(components):
        plot_df['Artist'] = df_for_plot['artists']
    else:
        plot_df['Artist'] = 'Unknown Artist'

    fig = px.scatter_3d(plot_df, x='PC1', y='PC2', z='PC3',
                        color='Genre', hover_data=['Track', 'Artist'],
                        title="3D Interactive Visualization of Tracks by Genre",
                        labels={'PC1': 'First Principal Component',
                                'PC2': 'Second Principal Component',
                                'PC3': 'Third Principal Component'})
    fig.update_layout(
        scene=dict(
            xaxis_title='PC1',
            yaxis_title='PC2',
            zaxis_title='PC3'
        ),
        width=1200, # Adjusted width for better display
        height=800, # Adjusted height for better display
        showlegend=True,
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.85
        )
    )
    return fig

def recommend_tracks(track_index, df, latent_features, knn, n_neighbors_knn=30, n_recommendations_display=9):
    """
    Recommends tracks similar to a given track.
    Args:
        track_index (int): Index of the track to find recommendations for.
        df (DataFrame): The original DataFrame (or processed one) with track details.
        latent_features (NumPy array): Latent features of all tracks.
        knn (NearestNeighbors): Trained KNN model.
        n_neighbors_knn (int): Number of neighbors to query from KNN.
        n_recommendations_display (int): Number of unique recommendations to display.
    Returns:
        DataFrame: DataFrame containing recommended tracks.
    """
    if not (0 <= track_index < len(df)):
        st.error(f"Selected track index ({track_index}) is out of bounds. Please select a valid track.")
        return pd.DataFrame()

    if latent_features.shape[0] == 0 or knn is None:
        st.warning("Latent features or KNN model not loaded. Cannot provide recommendations.")
        return pd.DataFrame()

    track_vector = latent_features[track_index].reshape(1, -1)
    distances, indices = knn.kneighbors(track_vector, n_neighbors=n_neighbors_knn)
    
    # Flatten indices and remove the first one (which is the track itself)
    similar_indices = indices.flatten()[1:]
    
    # Ensure indices are within bounds of df
    valid_similar_indices = [idx for idx in similar_indices if idx < len(df)]

    similar_tracks = df.iloc[valid_similar_indices]
    
    # Drop duplicates by track name and artist, then take the top N
    unique_tracks = similar_tracks.drop_duplicates(subset=['track_name', 'artists']).head(n_recommendations_display)
    
    return unique_tracks[['track_name', 'artists', 'track_genre', 'track_id']] # Include track_id for embedding

# --- Streamlit UI ---
with tab1:
    st.subheader("Get Track Recommendations")
    
    # Add a spinner while loading data and models
    with st.spinner("Loading data and models..."):
        df_main = load_data()
        latent_features_main = load_latent_features()
        knn_main = load_knn_model()

    # Create a selectbox for track selection
    # Ensure df_main is not empty before creating track_options
    if not df_main.empty:
        track_options = [f"{i} - {row['track_name']} by {row['artists']}" for i, row in df_main.iterrows()]
        selected_option = st.selectbox("Select a Track:", track_options)
        
        if selected_option: # Ensure an option is selected
            track_index = int(selected_option.split(" - ")[0])

            selected_track_info = df_main.iloc[track_index]
            st.markdown(f"**Selected:** {selected_track_info['track_name']} by {selected_track_info['artists']} | Genre: *{selected_track_info['track_genre']}*")

            # Display Spotify Embed for the selected track
            if 'track_id' in selected_track_info and pd.notna(selected_track_info['track_id']):
                track_id = selected_track_info['track_id']
                # The corrected Spotify embed URL:
                components.html(
                    f"""
                    <iframe style="border-radius:12px" 
                            src="https://open.spotify.com/embed/track/{track_id}?utm_source=generator"
                            width="100%" height="152" frameBorder="0" 
                            allowfullscreen="" 
                            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
                            loading="lazy">
                    </iframe>
                    """,
                    height=170 # Adjust height slightly to accommodate iframe padding/margin
                )
            else:
                st.warning("Track ID not available for the selected track - can't play preview.")

            st.write("**Top Recommendations:**")
            recs = recommend_tracks(track_index, df_main, latent_features_main, knn_main)

            # Custom CSS for dark cards
            st.markdown("""
            <style>
                .dark-card {
                    background-color: #1a1a1a !important; /* Slightly lighter black for contrast */
                    padding: 15px;
                    border-radius: 10px;
                    margin-bottom: 20px;
                    color: white !important;
                    box-shadow: 0 4px 8px rgba(0,0,0,0.3);
                    border: 1px solid #333; /* Subtle border */
                }
                .dark-card iframe {
                    border-radius: 5px;
                }
            </style>
            """, unsafe_allow_html=True)

            # Display recommended tracks with Spotify embeds
            if not recs.empty:
                cols = st.columns(3) # Display in 3 columns for better use of space
                for i, row_data in enumerate(recs.itertuples()): # Use itertuples for slightly better performance
                    with cols[i % 3]:
                        if 'track_id' in row_data and pd.notna(row_data.track_id):
                            components.html(
                                f"""
                                <div class="dark-card">
                                    <iframe style="border-radius:12px" 
                                            src="https://open.spotify.com/embed/track/{row_data.track_id}?utm_source=generator"
                                            width="100%" height="152" frameBorder="0" 
                                            allowfullscreen="" 
                                            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
                                            loading="lazy">
                                    </iframe>
                                </div>
                                """,
                                height=170 # Adjust height slightly
                            )
                        else:
                            st.markdown(f"""
                            <div class="dark-card">
                                <strong>{row_data.track_name}</strong><br>
                                <em>{row_data.artists}</em><br>
                                Genre: {row_data.track_genre}<br>
                                <small>No Spotify preview available</small>
                            </div>
                            """, unsafe_allow_html=True)
            else:
                st.info("No recommendations found for the selected track. Try selecting a different track or check your data/model.")
        else:
            st.info("Please select a track to get recommendations.")
    else:
        st.warning("No data loaded to display recommendations. Please check the data source and ensure 'df_processed.pkl' exists.")


with tab2:
    st.subheader("3D PCA Visualization of Tracks by Genre")
    
    with st.spinner("Preparing visualizations..."):
        df_viz = load_data() # Load data again for visualization tab (cached, so fast)
        latent_features_viz = load_latent_features() # Load latent features again (cached, so fast)
    
    if not df_viz.empty and latent_features_viz.shape[0] > 0:
        fig_3d = plot_latent_3d(latent_features_viz, df_viz)
        st.plotly_chart(fig_3d, use_container_width=True)

        st.subheader("Feature Correlation Heatmap")
        fig_heatmap = plot_heatmap(df_viz, numeric_features)
        st.plotly_chart(fig_heatmap, use_container_width=True)
    else:
        st.warning("Cannot display visualizations: Data or latent features are not available. Please ensure data is loaded correctly.")